apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  # 以NodePort方式暴露端口，NodePort 默认范围是 30000-32767，可通过向apiserver添加参数 –service-node-port-range=1-65535
  type: NodePort
  ports:
    - port: 30001
      nodePort: 30001
      targetPort: 80
  selector:
    app: nginx
